id: I77DB8738
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:07:21+00:00'
last_modified: '2022-06-16T04:00:44.632626+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1067
  title: མགོན་པོ་ཕྱག་དྲུག་པའི་གཏོར་སྒྲུབ་འདོན་བསྒྲིགས་རྗེ་འཇམ་དབྱངས་བཞད་པའི་གསུངས་རྒྱུན་ལྟར་བཀོད་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3BB7:
      image_group_id: I1CZ1425
      title: Volume 1 of mgon po phyag drug pa'i gtor sgrub 'don bsgrigs rje 'jam
        dbyangs bzhad pa'i gsungs rgyun ltar bkod pa
      total_pages: 12
      order: 1
      base_file: 3BB7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
